// generated by cdktf get
// joatmon08/kubernetes/google/0.4.0/
import { TerraformModule } from 'cdktf';
import { Construct } from 'constructs';
export interface KubernetesOptions {
  /**
   * ops toggle to enable highmem instance types
   * @default false
   */
  readonly enableHighmemNodepool?: boolean;
  /**
   * GCP Zone to deploy
   * @default "us-central1-a"
   */
  readonly zone?: string;
  /**
   * google service account id for workload identity
   */
  readonly serviceAccountId?: string;
  /**
   * version of stack. appended to name.
   */
  readonly versionIdentifier?: string;
  /**
   * GCP Project
   */
  readonly project?: string;
  /**
   * environment of gke cluster. prepended to name.
   */
  readonly environment?: string;
}
export class Kubernetes extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, options: KubernetesOptions) {
    super(scope, id, {
      source: 'joatmon08/kubernetes/google',
      version: '0.4.0',
    });
    this.enableHighmemNodepool = options.enableHighmemNodepool;
    this.zone = options.zone;
    this.serviceAccountId = options.serviceAccountId;
    this.versionIdentifier = options.versionIdentifier;
    this.project = options.project;
    this.environment = options.environment;
  }
  public get enableHighmemNodepool(): boolean | undefined {
    return this.inputs['enable_highmem_nodepool'] as boolean | undefined;
  }
  public set enableHighmemNodepool(value: boolean | undefined) {
    this.inputs['enable_highmem_nodepool'] = value;
  }
  public get zone(): string | undefined {
    return this.inputs['zone'] as string | undefined;
  }
  public set zone(value: string | undefined) {
    this.inputs['zone'] = value;
  }
  public get serviceAccountId(): string | undefined {
    return this.inputs['service_account_id'] as string | undefined;
  }
  public set serviceAccountId(value: string | undefined) {
    this.inputs['service_account_id'] = value;
  }
  public get versionIdentifier(): string | undefined {
    return this.inputs['version_identifier'] as string | undefined;
  }
  public set versionIdentifier(value: string | undefined) {
    this.inputs['version_identifier'] = value;
  }
  public get project(): string | undefined {
    return this.inputs['project'] as string | undefined;
  }
  public set project(value: string | undefined) {
    this.inputs['project'] = value;
  }
  public get environment(): string | undefined {
    return this.inputs['environment'] as string | undefined;
  }
  public set environment(value: string | undefined) {
    this.inputs['environment'] = value;
  }
  public get k8SClusterOutput(): string {
    return this.interpolationForOutput('k8s_cluster')
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
